version: "3.9"

services:
  db:
    container_name: eCatalogos-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eCatalogos
      MYSQL_DATABASE: eCatalogos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -peCatalogos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    container_name: eCatalogos-api
    build: ./api
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://root:eCatalogos@db:3306/eCatalogos
      - DOCKER=YES
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev && npm start"

volumes:
  db_data:
